# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcoauth/v1/enums.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'grpcoauth/v1/enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpcoauth/v1/enums.proto\x12\x0cgrpcoauth.v1*h\n\tGrantType\x12\x1a\n\x16GRANT_TYPE_UNSPECIFIED\x10\x00\x12!\n\x1dGRANT_TYPE_AUTHORIZATION_CODE\x10\x01\x12\x1c\n\x18GRANT_TYPE_REFRESH_TOKEN\x10\x02*N\n\x08RoleType\x12\x19\n\x15ROLE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fROLE_TYPE_ADMIN\x10\x01\x12\x12\n\x0eROLE_TYPE_USER\x10\x02*`\n\x0cResponseType\x12\x1d\n\x19RESPONSE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15RESPONSE_TYPE_SUCCESS\x10\x01\x12\x16\n\x12RESPONSE_TYPE_FAIL\x10\x02*j\n\tLoginType\x12\x1a\n\x16LOGIN_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11LOGIN_TYPE_NATIVE\x10\x01\x12\x14\n\x10LOGIN_TYPE_KAKAO\x10\x02\x12\x14\n\x10LOGIN_TYPE_NAVER\x10\x03*>\n\tTokenType\x12\x1a\n\x16TOKEN_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11TOKEN_TYPE_BEARER\x10\x01\x42\xab\x01\n\x10\x63om.grpcoauth.v1B\nEnumsProtoP\x01Z:github.com/vet1ments/grpcoauth/go/grpcoauth/v1;grpcoauthv1\xa2\x02\x03GXX\xaa\x02\x0cGrpcoauth.V1\xca\x02\x0cGrpcoauth\\V1\xe2\x02\x18Grpcoauth\\V1\\GPBMetadata\xea\x02\rGrpcoauth::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcoauth.v1.enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.grpcoauth.v1B\nEnumsProtoP\001Z:github.com/vet1ments/grpcoauth/go/grpcoauth/v1;grpcoauthv1\242\002\003GXX\252\002\014Grpcoauth.V1\312\002\014Grpcoauth\\V1\342\002\030Grpcoauth\\V1\\GPBMetadata\352\002\rGrpcoauth::V1'
  _globals['_GRANTTYPE']._serialized_start=42
  _globals['_GRANTTYPE']._serialized_end=146
  _globals['_ROLETYPE']._serialized_start=148
  _globals['_ROLETYPE']._serialized_end=226
  _globals['_RESPONSETYPE']._serialized_start=228
  _globals['_RESPONSETYPE']._serialized_end=324
  _globals['_LOGINTYPE']._serialized_start=326
  _globals['_LOGINTYPE']._serialized_end=432
  _globals['_TOKENTYPE']._serialized_start=434
  _globals['_TOKENTYPE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
