# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oauthapp/v1/login.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'oauthapp/v1/login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import httpbody_pb2 as google_dot_api_dot_httpbody__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17oauthapp/v1/login.proto\x12\x0boauthapp.v1\x1a\x19google/api/httpbody.proto\x1a\x1cgoogle/api/annotations.proto\"1\n\x13GetLoginPageRequest\x12\x1a\n\x08\x63ontinue\x18\x01 \x01(\tR\x08\x63ontinue\".\n\x0cLoginRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n\x02pw\x18\x02 \x01(\tR\x02pw\";\n\x0f\x43\x61llbackRequest\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\x12\x14\n\x05state\x18\x02 \x01(\tR\x05state2\xb3\x01\n\x0cLoginService\x12V\n\x0cGetLoginPage\x12 .oauthapp.v1.GetLoginPageRequest\x1a\x14.google.api.HttpBody\"\x0e\x82\xd3\xe4\x93\x02\x08\x12\x06/login\x12K\n\x05Login\x12\x19.oauthapp.v1.LoginRequest\x1a\x14.google.api.HttpBody\"\x11\x82\xd3\xe4\x93\x02\x0b\"\x06/login:\x01*2l\n\x15SocialCallbackService\x12S\n\x08\x43\x61llback\x12\x1c.oauthapp.v1.CallbackRequest\x1a\x14.google.api.HttpBody\"\x13\x82\xd3\xe4\x93\x02\r\x12\x0b/callback/*B\xa4\x01\n\x0f\x63om.oauthapp.v1B\nLoginProtoP\x01Z8github.com/vet1ments/grpcoauth/go/oauthapp/v1;oauthappv1\xa2\x02\x03OXX\xaa\x02\x0bOauthapp.V1\xca\x02\x0bOauthapp\\V1\xe2\x02\x17Oauthapp\\V1\\GPBMetadata\xea\x02\x0cOauthapp::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oauthapp.v1.login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.oauthapp.v1B\nLoginProtoP\001Z8github.com/vet1ments/grpcoauth/go/oauthapp/v1;oauthappv1\242\002\003OXX\252\002\013Oauthapp.V1\312\002\013Oauthapp\\V1\342\002\027Oauthapp\\V1\\GPBMetadata\352\002\014Oauthapp::V1'
  _globals['_LOGINSERVICE'].methods_by_name['GetLoginPage']._loaded_options = None
  _globals['_LOGINSERVICE'].methods_by_name['GetLoginPage']._serialized_options = b'\202\323\344\223\002\010\022\006/login'
  _globals['_LOGINSERVICE'].methods_by_name['Login']._loaded_options = None
  _globals['_LOGINSERVICE'].methods_by_name['Login']._serialized_options = b'\202\323\344\223\002\013\"\006/login:\001*'
  _globals['_SOCIALCALLBACKSERVICE'].methods_by_name['Callback']._loaded_options = None
  _globals['_SOCIALCALLBACKSERVICE'].methods_by_name['Callback']._serialized_options = b'\202\323\344\223\002\r\022\013/callback/*'
  _globals['_GETLOGINPAGEREQUEST']._serialized_start=97
  _globals['_GETLOGINPAGEREQUEST']._serialized_end=146
  _globals['_LOGINREQUEST']._serialized_start=148
  _globals['_LOGINREQUEST']._serialized_end=194
  _globals['_CALLBACKREQUEST']._serialized_start=196
  _globals['_CALLBACKREQUEST']._serialized_end=255
  _globals['_LOGINSERVICE']._serialized_start=258
  _globals['_LOGINSERVICE']._serialized_end=437
  _globals['_SOCIALCALLBACKSERVICE']._serialized_start=439
  _globals['_SOCIALCALLBACKSERVICE']._serialized_end=547
# @@protoc_insertion_point(module_scope)
